inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - node_modules/**/*
    - bin/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/robots.rb
# We're not actually using Rails methods here.
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
