inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - node_modules/**/*
    - bin/webpack
    - bin/webpack-dev-server
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/robots.rb
