language: ruby
rvm:
  - 2.4.1
dist: trusty
bundler_args: --without deployment
sudo: false
cache: bundler
node_js:
  - "7"
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
  - bundle install
  - bundle binstubs webpacker
  - bundle exec rails webpacker:check_webpack_binstubs
  - bundle exec rails webpacker:compile
  - bundle exec rails webpacker
before_script:
  - bundle exec rails webpacker:verify_install
  - RAILS_ENV=test bundle exec rake assets:precompile
