language: ruby
rvm:
  - 2.3.3
  - 2.4.0
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
# This is the behaviour we want, so no sense in overriding it
bundler_args: --without deployment
sudo: false
cache: bundler
matrix:
  allow_failures:
  - rvm: 2.4.0
