language: ruby
rvm:
- 2.5.1
dist: xenial
bundler_args: "--deployment"
sudo: required
addons:
  apt:
    packages:
    - haveged
    - google-chrome-stable
    - chromium-chromedriver
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
node_js:
- '10'
env:
  global:
  - TZ=Europe/London
  - PATH=$PATH:/usr/lib/chromium-browser/
  - DISPLAY=:99.0
before_install:
- sh -e /etc/init.d/xvfb start
install:
- nvm install node
- node -v
- npm i -g yarn
- yarn
- bundle install
before_script:
- bundle exec rails webpacker:verify_install
script:
- bundle exec rubocop
- bundle exec rake
before_deploy: "./compile-build"
deploy:
  provider: releases
  api_key:
    secure: Geli5ElnzDGbg1Q9hMeT1SChitOi2by3Zc0HKMeMDe0n8c1wu78yEOFDFrPycfRB5Z308Zy0mzEeDQNt/heboU+YpX2J2RpUC6VwvKgGKs14odyyvyjli5ihJCjqh2dUnn4qsSbbqts/pOB2mmDMBy5XEZZUF9So1/uvm6DmTo9CSjjGZASgxNC/Dg0O5Pkj2D+kVtAxwxF+NGFfBK+kijfHFb9GUkINBrJ3s8BYgPDTEM8pQIzizt2VzRGO/FSdnzfJUD4H12XZIyKFmaKKaFfvWxcMXaacLRGkT3hdfJ9TPUPzjq8At+CzcWi2LvXLmEBJPBQcqppKRa3Zmg0az/2jGJ7NbeKZ964a5r6Xmuu1q6eWWIdyQZ9AYydPJ/siaPqTb5DlgRfaXOB8oCzsiVNslJeI1fBkjZ0lxQz5A5DWwQlHC5Yck7jdTz7JcTScSH6DueAhOSLsvBa8OnYM0GmRWuZuOV5ibcOk5limG7oVvKMJ+JiPOb9+0Myk5scm33B6WqnV1mllDV9uEs7h2K5DsJdOk6O08djlzHMHb2GwrV5vzwBG8kjq5bVAxx8Ds+0JVNHwMp7BJzAaZssTHMJwmPirhpEpEB8W+dQG0E5LEo0LcMUNZ5k2UWrY9qjcOl6ANU9D9yBFGqc9npW+G9Tlxc1yKqNTvSH8ujQA7rE=
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: radome/limber
