language: ruby
rvm:
  - 2.4.1
dist: trusty
bundler_args: --without deployment
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
node_js:
  - "7"
env: TZ=Europe/London
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
  - bundle install
before_script:
  - bundle exec rails webpacker:verify_install
  - RAILS_ENV=test bundle exec rake assets:precompile
