language: ruby
rvm:
- 2.4.1
dist: trusty
bundler_args: "--deployment"
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
node_js:
- '7'
env: TZ=Europe/London
install:
- nvm install node
- node -v
- npm i -g yarn
- yarn
- bundle install
before_script:
- bundle exec rails webpacker:verify_install
- RAILS_ENV=test bundle exec rake assets:precompile
before_deploy: "./compile-build"
deploy:
  provider: releases
  api_key:
    secure: vKjTnGZP/J2QDHwQFWv+osdCoZE27ntD7ZuysamepoX4mC5mmrY+Qu5Lx0P8FbSMx2LpMmX4hgcA6myiAbt36g4pUOyUHtUMsFjoy09rTfEfh3oZgQ2EfTF8AWrryjseh1YHi6TKC0DJY4LTmmKS8GlwjMSBr8eRXFgSHKbHTjWP2h8TyKXgZ0/SLjflNQLHsfmzx5S4bdCPN9Tjgp/cGQ7CgW47dpmDkPYEaKFh467OyVjrzR95HXTUZYUFFxSTzWu6hgbxzaMMg5tsXf6H0tHmQrZSwnOrYYl/2KDs1Kdn698yUZzIgmD8Zj8FRbTXQpmhASOGegDhQZfOx6ABBg0YqO1fKImcMSBrpfqB9Xt5AmH/VC488pWud7DgjMsYkMdSnTVCP4wLvq0j1JS9kmx7H2kwZDvLtQrqq3D+nW9EuoaOLcr6bVJMwJ22KcK9i2BvVCWV46dpp3d4TDSEXDV3lyZ3Q8BYRF9QNQLjCZSWqS3ay/yvCZLIZjS9E+O/nXrA4kh/seTyDE1LAimqHQJt2Xh6/JoU+5tLfOcebmzmZDWHn8aeP79TMNyb3jWbs23tpqpQtrc3kcSsFvyfWr/AB2INXVNbishuzx7XWrVsrrk4/SUMNv8uAVcbhDohmwBDJqctnThnCp7Upkt8uV6mWr3qD6n2UsLrpLvBw5g=
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
