language: ruby
rvm:
  - 2.4.1
dist: trusty
bundler_args: --without deployment
sudo: false
cache: bundler
node_js:
  - "7"
install:
  - bundle install
  - nvm install node
  - npm i -g yarn
before_script:
  - bundle exec rails webpacker:verify_install
  - RAILS_ENV=test bundle exec rake assets:precompile
