---
LB Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LB Shear:
  :asset_type: plate
  :parents:
  - LB Cherrypick
LB Post Shear:
  :asset_type: plate
  :parents:
  - LB Shear
LB End Prep:
  :asset_type: plate
  :parents:
  - LB Post Shear
  - LB cDNA XP
LB Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 6
  :tag_layout_templates:
  - Illumina pipeline tagging
  - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
  - hWGS and RNAseq UDI tag layout v3
  - pWGS UDI tag layout v2 A
  - pWGS UDI tag layout v2 B
  - pWGS UDI tag layout v2 C
  - pWGS UDI tag layout v2 D
  - TS_pWGSA_UDI96
  - TS_pWGSB_UDI96
  - TS_pWGSC_UDI96
  - TS_pWGSD_UDI96
  - TSRNAhWGS_UDI96
  :parents:
  - LB End Prep
LB Lib PCR-XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :suggest_library_pass_for:
  - limber_wgs
  - limber_lcmb
  - limber_rnaa
  :parents:
  - LB Lib PCR
LB Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LB Lib PCR-XP
  - PF Lib XP2
LB Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubeNoQcPurpose
  :creator_class: LabwareCreators::FinalTube
  :presenter_class: Presenters::FinalTubePresenter
  :default_printer_type: :tube
  :parents:
  - LB Lib Pool
