# This configuration file is for the Bespoke Chromium Automated pipeline for VDJ option TCR
# library type requests.
---
LBC TCR Dil 1:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :creator_class: LabwareCreators::FixedNormalisedPlate
  :parents:
  - LBC Cherrypick
  :expected_request_types:
  - limber_chromium_bespoke
  :expected_library_types:
  - Chromium single cell TCR
  :fixed_normalisation:
  - source_volume_ul: 2
    diluent_volume_ul: 33
  :file_links:
  - name: 'Download Hamilton Cherrypick to ?? CSV'
    id: 'hamilton_cherrypick_to_??'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
