# This configuration file is for the Bespoke Chromium Automated pipeline for 5 prime
# library type requests.
---
LBC 5p GEX Dil:
  :asset_type: plate
  :presenter_class: Presenters::BinnedNormalisedPlatePresenter
  :creator_class: LabwareCreators::BinnedNormalisedPlate
  :parents:
  - LBC Cherrypick
  :expected_request_types:
  - limber_chromium_bespoke
  :expected_library_types:
  - Chromium single cell 5 prime
  :dilutions:
    :target_amount_ng: 50
    :target_volume: 20
    :minimum_source_volume: 0.2
    :bins:
    - colour: 1
      pcr_cycles: 16
      max: 26
    - colour: 2
      pcr_cycles: 14
      min: 26
  :file_links:
  - name: 'Download Hamilton Cherrypick to 5 prime Dilution CSV'
    id: 'hamilton_cherrypick_to_5p_gex_dilution'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC 5p GEX Frag 2XP:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - LBC 5p GEX Dil
  :file_links:
  - name: 'Download Hamilton Dilution to Frag 2XP CSV'
    id: 'hamilton_gex_dil_to_gex_frag_2xp'
LBC 5p GEX LigXP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::CustomTaggedPlate
  :parents:
  - LBC 5p GEX Frag 2XP
  :tags_per_well: 4
  :file_links:
  - name: 'Download Hamilton Frag 2XP to LigXP CSV'
    id: 'hamilton_gex_frag_2xp_to_gex_ligxp'
LBC 5p GEX PCR 2XP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :parents:
  - LBC 5p GEX LigXP
  :suggest_library_pass_for:
  - limber_chromium_bespoke
  :file_links:
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC 5p GLibPS:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LBC 5p GEX PCR 2XP
