# This configuration file is for the Bespoke Chromium Aggregation and Bespoke
# Chromium Automated pipelines.
# LBC Stock plates are submitted to the Aggregation pipeline to be combined
# through LBC Aggregate plates into LBC Cherrypick plates, and then the LBC
# Cherrypick plates are subnitted to the Chromium Automated pipeline for library
# preparation and sequencing.
---
LBC Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
  :default_printer_type: :plate_a
LBC Aggregate:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :creator_class: LabwareCreators::TenStamp
  :default_printer_type: :plate_a
  :parents:
  - LBC Stock
LBC Cherrypick:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :creator_class: LabwareCreators::TenStamp
  :file_links: [
    {
      name: 'Download Hamilton Aggregate Cherry Pick CSV',
      id: 'hamilton_aggregate_cherry_pick'
    }
  ]
  :default_printer_type: :plate_a
  :parents:
  - LBC Aggregate
LBC GEX Dil:
  :asset_type: plate
  :presenter_class: Presenters::ConcentrationBinnedPlatePresenter
  :creator_class: LabwareCreators::ConcentrationBinnedPlate
  :default_printer_type: :plate_a
  # Currently both manual and automated Cherrypick plates are possible parents
  # until we can use library type to restrict them.
  :parents:
  - LBC Cherrypick
  - LBB Cherrypick
  :concentration_binning: {
    source_volume: 10,
    diluent_volume: 25,
    bins: [
      {
        colour: 1,
        pcr_cycles: 16,
        max: 25
      },
      {
        colour: 2,
        pcr_cycles: 12,
        min: 25,
        max: 500
      },
      {
        colour: 3,
        pcr_cycles: 8,
        min: 500
      }
    ]
  }
LBC GEX Frag 2XP:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :default_printer_type: :plate_a
  :parents:
  - LBC GEX Dil
LBC GEX LigXP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::CustomTaggedPlate
  :default_printer_type: :plate_a
  :parents:
  - LBC GEX Frag 2XP
  :tags_per_well: 4
LBC GEX PCR 2XP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter # Q. do they want to see tags?
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :parents:
  - LBC GEX LigXP
  :suggest_library_pass_for:
  - limber_chromium_bespoke
LBC GEX Lib Pool Stock:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LBC GEX PCR 2XP
