# This configuration file is for the Bespoke Chromium Automated pipeline for VDJ option BCR
# library type requests.
---
LBC BCR Dil 1:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :creator_class: LabwareCreators::FixedNormalisedPlate
  :parents:
  - LBC Cherrypick
  :expected_request_types:
  - limber_chromium_bespoke
  :expected_library_types:
  - Chromium single cell BCR
  :dilutions:
    :source_volume: 2
    :diluent_volume: 33
  :file_links:
  - name: 'Download Hamilton Cherrypick to BCR Dilution 1 CSV'
    id: 'hamilton_cherrypick_to_bcr_dilution1'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC BCR Enrich1 1XSPRI:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - LBC BCR Dil 1
  :file_links:
  - name: 'Download Hamilton BCR Dil 1 to BCR Enrich1 1XSPRI CSV'
    id: 'hamilton_lbc_bcr_dil_1_to_lbc_bcr_enrich1_1xspri'
LBC BCR Enrich2 2XSPRI:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - LBC BCR Enrich1 1XSPRI
  :file_links:
  - name: 'Download Hamilton BCR Enrich1 1XSPRI to BCR Enrich2 2XSPRI CSV'
    id: 'hamilton_lbc_bcr_enrich1_1xspri_to_lbc_bcr_enrich2_2xspri'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC BCR Dil 2:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :creator_class: LabwareCreators::ConcentrationNormalisedPlate
  :parents:
  - LBC BCR Enrich2 2XSPRI
  :dilutions:
    :target_amount_ng: 50
    :target_volume: 20
    :minimum_source_volume: 0.2
  :file_links:
  - name: 'Download Hamilton BCR Enrich2 2XSPRI to BCR Dil 2 CSV'
    id: 'hamilton_lbc_bcr_enrich2_2xspri_to_lbc_bcr_dil_2'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC BCR Post Lig 1XSPRI:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::CustomTaggedPlate
  :parents:
  - LBC BCR Dil 2
  :tags_per_well: 4
  :file_links:
  - name: 'Download Hamilton BCR Dil 2 to BCR Post Lig 1XSPRI CSV'
    id: 'hamilton_lbc_bcr_dil_2_to_lbc_bcr_post_lig_1xspri'
LBC BCR Post PCR:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - LBC BCR Post Lig 1XSPRI
  :file_links:
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC BCR LibPS:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LBC BCR Post PCR
