# This configuration file is for the Bespoke Chromium Automated pipeline for 3 prime
# version 3 library type requests.
---
LBC 3pV3 GEX Dil:
  :asset_type: plate
  :presenter_class: Presenters::ConcentrationBinnedPlatePresenter
  :creator_class: LabwareCreators::ConcentrationBinnedPlate
  :parents:
  - LBC Cherrypick
  :expected_request_types:
  - limber_chromium_bespoke
  :expected_library_types:
  - Chromium single cell 3 prime v3
  :dilutions:
    :source_volume: 10
    :diluent_volume: 25
    :bins:
    - colour: 1
      pcr_cycles: 16
      max: 24
    - colour: 2
      pcr_cycles: 12
      min: 25
      max: 499
    - colour: 3
      pcr_cycles: 8
      min: 500
      max: 1499
    - colour: 4
      pcr_cycles: 5
      min: 1500
  :file_links:
  - name: 'Download Hamilton Cherrypick to Sample Dilution CSV'
    id: 'hamilton_cherrypick_to_sample_dilution'
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC 3pV3 GEX Frag 2XP:
  :asset_type: plate
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - LBC 3pV3 GEX Dil
  :file_links:
  - name: 'Download Hamilton Dilution to Frag 2XP CSV'
    id: 'hamilton_gex_dil_to_gex_frag_2xp'
LBC 3pV3 GEX LigXP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::CustomTaggedPlate
  :parents:
  - LBC 3pV3 GEX Frag 2XP
  :tags_per_well: 4
  :file_links:
  - name: 'Download Hamilton Frag 2XP to LigXP CSV'
    id: 'hamilton_gex_frag_2xp_to_gex_ligxp'
LBC 3pV3 GEX PCR 2XP:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :parents:
  - LBC 3pV3 GEX LigXP
  :suggest_library_pass_for:
  - limber_chromium_bespoke
  :file_links:
  - name: Download Concentration (ng/ul) CSV
    id: concentrations_ngul
LBC 3pV3 GLibPS:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LBC 3pV3 GEX PCR 2XP
