---
GnT Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
GnT scDNA:
  :asset_type: plate
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - GnT Stock
  :expected_request_types:
  - limber_gnt_picoplex
  - limber_gnt_mda
GnT Pico-XP:
  :asset_type: plate
  :parents:
  - GnT scDNA
  :expected_request_types:
  - limber_gnt_picoplex
GnT Pico End Prep:
  :asset_type: plate
  :parents:
  - GnT Pico-XP
GnT Pico Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :suggest_library_pass_for:
  - limber_gnt_picoplex
  :parents:
  - GnT Pico End Prep
GnT MDA Norm:
  :presenter_class: Presenters::UntaggedPlatePassingPresenter
  :asset_type: plate
  :parents:
  - GnT scDNA
  :expected_request_types:
  - limber_gnt_mda
  :suggest_library_pass_for:
  - limber_gnt_mda
GnT Pico Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :parents:
  - GnT Pico Lib PCR
GnT Pico Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
  :parents:
  - GnT Pico Lib Pool
