---
LHR Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :default_printer_type: :plate_a
  :label_template: plate_label_lhr_cherrypick
  :presenter_class: Presenters::StockPlatePresenter
LHR XP:
  :asset_type: plate
LHR End Prep:
  :asset_type: plate
LHR Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
  - Illumina pipeline tagging
  - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
  - TS_pWGSA_UDI96
  - TS_pWGSB_UDI96
  - TS_pWGSC_UDI96
  - TS_pWGSD_UDI96
  - TS_pWGSA_UDI96v2
  - TSISC_UDI96
LHR Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
LHR Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube