---
scRNA Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
scRNA cDNA-XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - scRNA Stock
scRNA End Prep:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - scRNA cDNA-XP
scRNA Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 8
  :parents:
  - scRNA End Prep
  :tag_layout_templates:
  - Illumina pipeline tagging
  - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
  :suggest_library_pass_for:
  - limber_scrna
scRNA Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib PCR
scRNA Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib Pool
scRNA Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubeNoQcPurpose
  :creator_class: LabwareCreators::FinalTube
  :presenter_class: Presenters::FinalTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib Pool XP
