---
Limber Bespoke PCR Free:
  filters:
    request_type_keys:
    - limber_pcr_free_bespoke
    library_type_names:
    - No PCR (Plate)
    - HiSeqX PCR free
    - DAFT-seq
    - TruSeq Custom Amplicon
  library_pass: LBB Lib-XP
  relationships:
    LBB Cherrypick: LBB Ligation Tagged
    LBB Ligation Tagged: LBB Lib-XP
Limber Bespoke PCR Free MX:
  filters:
    request_type_keys:
    - limber_multiplexing
  relationships:
    LBB Lib-XP: LBB Lib Pool Stock
    LBB Lib Pool Stock: LB Lib Pool Norm
