---
Limber Bespoke PCR:
  filters:
    request_type_keys:
    - limber_pcr_bespoke
    library_type_names:
    - Manual Standard WGS (Plate)
    - ChIP-Seq Auto
    - TruSeq mRNA (RNA Seq)
    - Small RNA (miRNA)
    - RNA-seq dUTP eukaryotic
    - RNA-seq dUTP prokaryotic
    - Standard
    - Ribozero RNA depletion
    - Ribozero RNA-seq (Bacterial)
    - Ribozero RNA-seq (HMR)
    - TraDIS
  library_pass: LBB Lib PCR-XP
  relationships:
    LBB Cherrypick: LBB Ligation
    LBB Ligation: LBB Lib PCR-XP
Limber Bespoke PCR MX:
  filters:
    request_type_keys:
    - limber_multiplexing
  relationships:
    LBB Lib PCR-XP: LBB Lib Pool Stock
    LBB Lib Pool Stock: LB Lib Pool Norm
