---
Heron:
  filters:
    request_type_key: limber_heron
    library_type: Heron
  library_pass: LHR Lib PCR
  relationships:
    LHR Cherrypick: LHR XP
    LHR XP: LHR End Prep
    LHR End Prep: LHR Lib PCR
    LHR Lib PCR: LHR Lib Pool
    LHR Lib Pool: LHR Lib Pool XP
    LHR Lib Pool XP: LB Lib Pool Norm
