---
Duplex Seq:
  filters:
    request_type_key: limber_duplex_seq
    library_type: duplex_seq
  library_pass: LDS Lib PCR XP
  relationships:
    LDS Cherrypick: LDS Stock XP
    LDS Stock XP: LDS AL Lib
    LDS AL Lib: LDS AL Lib Dil
    LDS AL Lib Dil: LDS Lib PCR
    LDS Lib PCR: LDS Lib PCR XP
    LDS Lib PCR XP: LDS Custom Pool
    LDS Custom Pool: LDS Custom Pool Norm
