---
LB Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LB Shear:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LB Cherrypick
LB Post Shear:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LB Shear
LB End Prep:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LB Post Shear
  - LB cDNA XP
LB Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PcrPresenter
  :form_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 6
  :tag_layout_templates:
  - Illumina pipeline tagging
  - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
  - hWGS and RNAseq UDI tag layout v3
  :parents:
  - LB End Prep
LB Lib PCR-XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :suggest_library_pass_for:
  - limber_wgs
  - limber_lcmb
  - limber_rnaa
  :parents:
  - LB Lib PCR
LB Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :form_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :expected_request_types:
  - limber_multiplexing
  :parents:
  - LB Lib PCR-XP
  - PF Lib XP2
LB Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubePurpose
  :form_class: LabwareCreators::FinalTube
  :presenter_class: Presenters::FinalTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - LB Lib Pool
LB Lib PrePool:
  :asset_type: plate
  :stock_plate: false
  :form_class: LabwareCreators::MultiPlatePool
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :csv_template: 'show_extended'
  :expected_request_types:
  - limber_isc
  - limber_reisc
  :parents:
  - LB Lib PCR-XP
LB Hyb:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :form_class: LabwareCreators::BaitedPlate
  :parents:
  - LB Lib PrePool
LB Cap Lib:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :parents:
  - LB Hyb
LB Cap Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :parents:
  - LB Cap Lib
LB Cap Lib PCR-XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :suggest_library_pass_for:
  - limber_isc
  - limber_reisc
  :parents:
  - LB Cap Lib PCR
LB Cap Lib Pool:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_b
  :transfer_template: 'Pool wells based on submission'
  :suggest_library_pass_for:
  - limber_isc
  - limber_reisc
  :parents:
  - LB Cap Lib PCR-XP
Cap Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubeNoQcPurpose
  :form_class: LabwareCreators::FinalTubeFromPlate
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - LB Cap Lib Pool
PF Cherrypicked:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StockPlatePresenter
PF Shear:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - PF Cherrypicked
PF Post Shear:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - PF Shear
PF Post Shear XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
PF End Prep:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
  :parents:
  - PF Post Shear
PF Lib:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::PermissivePresenter
  :form_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
  - 'NEXTflex-96 barcoded adapters tags in rows (first oligo: AACGTGAT)'
  - 'PF_adapters_UDI_96_A'
  - 'PF_adapters_UDI_96_B'
  - 'PF_adapters_UDI_96_C'
  - 'PF_adapters_UDI_96_D'
  :parents:
  - PF Post Shear XP
  - PF End Prep
PF Lib XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
PF Lib XP2:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StandardPresenter
  :suggest_library_pass_for:
  - limber_pcr_free
  :parents:
  - PF Lib XP
  - PF Lib
LB Custom Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :form_class: LabwareCreators::CustomPooledTubes
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :expected_request_types:
  - :none
  :parents:
  - LB Lib PCR-XP
LB Custom Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :form_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::FinalTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - LB Custom Pool
LBR Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LBR mRNA Cap:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LBR Cherrypick
LBR Frag:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LBR mRNA Cap
LB cDNA:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LBR Frag
LB cDNA XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - LB cDNA
scRNA Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
scRNA cDNA-XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - scRNA Stock
scRNA End Prep:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :parents:
  - scRNA cDNA-XP
scRNA Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PcrPresenter
  :form_class: LabwareCreators::TaggedPlate
  warnings:
    pcr_cycles_not_in:
      - 8
  :parents:
  - scRNA End Prep
  :tag_layout_templates:
  - Illumina pipeline tagging
  - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
scRNA Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :form_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib PCR
scRNA Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :form_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib Pool
scRNA Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubePurpose
  :form_class: LabwareCreators::FinalTube
  :presenter_class: Presenters::FinalTubePresenter
  :state_changer_class: StateChangers::DefaultStateChanger
  :default_printer_type: :tube
  :parents:
  - scRNA Lib Pool XP
