---
:large_insert_limit: 250
:searches:
  Find assets by barcode: 33ce1740-222b-11e4-ab60-44fb42fffecc
  Find project by name: 33d1c0c0-222b-11e4-ab60-44fb42fffecc
  Find study by name: 33d431c0-222b-11e4-ab60-44fb42fffecc
  Find sample by name: 33d6f0e0-222b-11e4-ab60-44fb42fffecc
  Find source assets by destination asset barcode: 33dae880-222b-11e4-ab60-44fb42fffecc
  Find user by login: 33ddceb0-222b-11e4-ab60-44fb42fffecc
  Find user by swipecard code: 33e0dbf0-222b-11e4-ab60-44fb42fffecc
  Find pulldown plates: 33e39b10-222b-11e4-ab60-44fb42fffecc
  Find Illumina-B plates: 33e68140-222b-11e4-ab60-44fb42fffecc
  Find Illumina-B plates for user: 33e91950-222b-11e4-ab60-44fb42fffecc
  Find Illumina-B stock plates: 33ebff80-222b-11e4-ab60-44fb42fffecc
  Find outstanding Illumina-B pre-PCR plates: 33f06c50-222b-11e4-ab60-44fb42fffecc
  Find Illumina-B tubes: 33f3c7b0-222b-11e4-ab60-44fb42fffecc
  Find pulldown plates for user: 33f6ade0-222b-11e4-ab60-44fb42fffecc
  Find pulldown stock plates: 33f8f7d0-222b-11e4-ab60-44fb42fffecc
  Find Illumina-A plates: 33fbb6f0-222b-11e4-ab60-44fb42fffecc
  Find Illumina-A stock plates: 33fe4f00-222b-11e4-ab60-44fb42fffecc
  Find Illumina-C tubes: 3401d170-222b-11e4-ab60-44fb42fffecc
  Find Illumina-C plates: 3404deb0-222b-11e4-ab60-44fb42fffecc
  Find lot by lot number: 34079dd0-222b-11e4-ab60-44fb42fffecc
  Find qcable by barcode: 340ad220-222b-11e4-ab60-44fb42fffecc
  Find robot by barcode: 340d6a30-222b-11e4-ab60-44fb42fffecc
  Find lot by batch id: 34107770-222b-11e4-ab60-44fb42fffecc
:transfer_templates:
  Transfer columns 1-1: 37a66f70-222b-11e4-ab60-44fb42fffecc
  Transfer columns 1-2: 37a89250-222b-11e4-ab60-44fb42fffecc
  Transfer columns 1-3: 37ad2630-222b-11e4-ab60-44fb42fffecc
  Transfer columns 1-4: 37af7020-222b-11e4-ab60-44fb42fffecc
  Transfer columns 1-6: 37b1e120-222b-11e4-ab60-44fb42fffecc
  Transfer columns 1-12: 37b67500-222b-11e4-ab60-44fb42fffecc
  Pool wells based on submission: 37b8bef0-222b-11e4-ab60-44fb42fffecc
  Custom pooling: 37ba1e80-222b-11e4-ab60-44fb42fffecc
  Transfer wells to MX library tubes by submission: 37bc8f80-222b-11e4-ab60-44fb42fffecc
  Transfer wells to specific tubes by submission: 37be6440-222b-11e4-ab60-44fb42fffecc
  Transfer from tube to tube by submission: 37c0ae30-222b-11e4-ab60-44fb42fffecc
  Transfer wells to specific tubes defined by submission: 37c20dc0-222b-11e4-ab60-44fb42fffecc
  Transfer between specific tubes: 37c3bb70-222b-11e4-ab60-44fb42fffecc
  Whole plate to tube: 37c67a90-222b-11e4-ab60-44fb42fffecc
  Flip Plate: 37cbf8d0-222b-11e4-ab60-44fb42fffecc
:printers:
  illumina_a:
    :plate_a: bac4df40-222b-11e4-8ce2-44fb42fffecc
    :plate_b: bac617c0-222b-11e4-8ce2-44fb42fffecc
    :tube: bac75040-222b-11e4-8ce2-44fb42fffecc
  illumina_b:
    :plate_a: bac135c0-222b-11e4-8ce2-44fb42fffecc
    :plate_b: bac2e370-222b-11e4-8ce2-44fb42fffecc
    :tube: bacaf9c0-222b-11e4-8ce2-44fb42fffecc
  limit: 5
  default_count: 2
:purposes: {}
:purpose_uuids: {}
:robots: {}
:locations:
  Library creation freezer: limber
  Pulldown freezer: illumina_a
:qc_purposes:
- Post Shear QC
- Lib PCR-XP QC
- Lib PCRR-XP QC
