
name: Linting
env:
  BUNDLE_WITHOUT: 'test development default'

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # Runs bundle install and caches gems. See the ruby_test.yml
                            # example if you need more control over bundler.
    - name: Run lint
      run: bundle exec rubocop --extra-details --display-style-guide --parallel

  eslint:
    name: EsLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install
      run: yarn install
    - name: Run yarn test
      run: yarn lint
