
name: Update Rubocop

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every sunday
    - cron:  '*/15 * * * *'

jobs:
  update_rubocop:
    if: (github.repository == 'jamesglover/limber')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # Runs bundle install and caches gems. See the ruby_test.yml
                            # example if you need more control over bundler.
    - name: Update Rubocop
      run: bin/update_rubocop
      # https://github.com/marketplace/actions/create-pull-request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Automatic Rubocop update
        branch: gh_action/update_rubocop
        delete-branch: true
        body: Automatic update via .github/workflows/update_rubocop.yml
